In [26]:
import pandas as pd
from string import ascii_uppercase as abc
import pickle

In [4]:
tablas = pd.read_html('https://web.archive.org/web/20221115040351/https://en.wikipedia.org/wiki/2022_FIFA_World_Cup')

In [17]:
tablas[12] ## GROUP A
tablas[19] ## GROUP B
tablas[26] ## GROUP C
tablas[33] ## GROUP D
tablas[40] ## GROUP E
tablas[47] ## GROUP F
tablas[54] ## GROUP G
tablas[61] ## GROUP H

   Pos      Teamvte  Pld  W  D  L  GF  GA  GD  Pts              Qualification
0    1     Portugal    0  0  0  0   0   0   0    0  Advance to knockout stage
1    2        Ghana    0  0  0  0   0   0   0    0  Advance to knockout stage
2    3      Uruguay    0  0  0  0   0   0   0    0                        NaN
3    4  South Korea    0  0  0  0   0   0   0    0                        NaN

In [22]:
tablas = pd.read_html('https://web.archive.org/web/20221115040351/https://en.wikipedia.org/wiki/2022_FIFA_World_Cup')

groups_dict = {}
for l, i in zip(abc, range(12, 68, 7)):
    df = tablas[i]
    df.rename(columns={df.columns[1]: 'Team'}, inplace=True)
    df.pop('Qualification')
    groups_dict[f'Group {l}'] = df

In [24]:
groups_dict['Group A']

   Pos         Team  Pld  W  D  L  GF  GA  GD  Pts
0    1    Qatar (H)    0  0  0  0   0   0   0    0
1    2      Ecuador    0  0  0  0   0   0   0    0
2    3      Senegal    0  0  0  0   0   0   0    0
3    4  Netherlands    0  0  0  0   0   0   0    0

In [27]:
with open('groups_dict', 'wb') as groups_fixture:
    pickle.dump(groups_dict, groups_fixture)